/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
// PledgedLottery
const deployedContracts = {
  31337: {
    PledgedLottery: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          "type": "constructor",
          "inputs": [
            { "name": "_stakingToken", "type": "address", "internalType": "address" },
            { "name": "_owner", "type": "address", "internalType": "address" }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "currentCycle",
          "inputs": [],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "cycleStartTime",
          "inputs": [],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "stakingToken",
          "inputs": [],
          "outputs": [{ "name": "", "type": "address", "internalType": "contract IERC20" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "stakeTokens",
          "inputs": [{ "name": "amount", "type": "uint256", "internalType": "uint256" }],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unstakeTokens",
          "inputs": [{ "name": "amount", "type": "uint256", "internalType": "uint256" }],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "buyTicket",
          "inputs": [],
          "outputs": [],
          "stateMutability": "payable"
        },
        {
          "type": "function",
          "name": "finalizeCycle",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "claimPrize",
          "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "claimStakingReward",
          "inputs": [{ "name": "cycle", "type": "uint256", "internalType": "uint256" }],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "getStakedAmount",
          "inputs": [
            { "name": "staker", "type": "address", "internalType": "address" },
            { "name": "cycle", "type": "uint256", "internalType": "uint256" }
          ],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getStakingReward",
          "inputs": [
            { "name": "staker", "type": "address", "internalType": "address" },
            { "name": "cycle", "type": "uint256", "internalType": "uint256" }
          ],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getUserTickets",
          "inputs": [{ "name": "user", "type": "address", "internalType": "address" }],
          "outputs": [{ "name": "", "type": "uint256[]", "internalType": "uint256[]" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getTicketInfo",
          "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }],
          "outputs": [
            {
              "name": "",
              "type": "tuple",
              "internalType": "struct PledgedLottery.TicketInfo",
              "components": [
                { "name": "cycle", "type": "uint256", "internalType": "uint256" },
                { "name": "owner", "type": "address", "internalType": "address" },
                { "name": "isRedeemed", "type": "bool", "internalType": "bool" },
                { "name": "prizeType", "type": "uint256", "internalType": "uint256" },
                { "name": "prizeAmount", "type": "uint256", "internalType": "uint256" }
              ]
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getCycleInfo",
          "inputs": [{ "name": "cycle", "type": "uint256", "internalType": "uint256" }],
          "outputs": [
            { "name": "totalStaked", "type": "uint256", "internalType": "uint256" },
            { "name": "totalTickets", "type": "uint256", "internalType": "uint256" },
            { "name": "totalSales", "type": "uint256", "internalType": "uint256" },
            { "name": "rewardPool", "type": "uint256", "internalType": "uint256" },
            { "name": "isFinalized", "type": "bool", "internalType": "bool" }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getCurrentCycleTimeLeft",
          "inputs": [],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "ownerOf",
          "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }],
          "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "owner",
          "inputs": [],
          "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
          "stateMutability": "view"
        },
        {
          "type": "event",
          "name": "CycleStarted",
          "inputs": [
            { "name": "cycle", "type": "uint256", "indexed": true, "internalType": "uint256" },
            { "name": "startTime", "type": "uint256", "indexed": false, "internalType": "uint256" }
          ],
          "anonymous": false
        },
        {
          "type": "event",
          "name": "TokensStaked",
          "inputs": [
            { "name": "staker", "type": "address", "indexed": true, "internalType": "address" },
            { "name": "amount", "type": "uint256", "indexed": false, "internalType": "uint256" },
            { "name": "cycle", "type": "uint256", "indexed": false, "internalType": "uint256" }
          ],
          "anonymous": false
        },
        {
          "type": "event",
          "name": "TicketMinted",
          "inputs": [
            { "name": "buyer", "type": "address", "indexed": true, "internalType": "address" },
            { "name": "tokenId", "type": "uint256", "indexed": true, "internalType": "uint256" },
            { "name": "cycle", "type": "uint256", "indexed": false, "internalType": "uint256" }
          ],
          "anonymous": false
        },
        {
          "type": "event",
          "name": "LotteryDrawn",
          "inputs": [
            { "name": "cycle", "type": "uint256", "indexed": true, "internalType": "uint256" },
            { "name": "totalWinners", "type": "uint256", "indexed": false, "internalType": "uint256" }
          ],
          "anonymous": false
        },
        {
          "type": "event",
          "name": "PrizeClaimed",
          "inputs": [
            { "name": "winner", "type": "address", "indexed": true, "internalType": "address" },
            { "name": "tokenId", "type": "uint256", "indexed": true, "internalType": "uint256" },
            { "name": "prizeAmount", "type": "uint256", "indexed": false, "internalType": "uint256" },
            { "name": "prizeType", "type": "uint256", "indexed": false, "internalType": "uint256" }
          ],
          "anonymous": false
        }
      ],
      "inheritedFunctions": {}
    },
    MockStakingToken: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          "type": "constructor",
          "inputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "name",
          "inputs": [],
          "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "symbol",
          "inputs": [],
          "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "decimals",
          "inputs": [],
          "outputs": [{ "name": "", "type": "uint8", "internalType": "uint8" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalSupply",
          "inputs": [],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "balanceOf",
          "inputs": [{ "name": "account", "type": "address", "internalType": "address" }],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "transfer",
          "inputs": [
            { "name": "to", "type": "address", "internalType": "address" },
            { "name": "amount", "type": "uint256", "internalType": "uint256" }
          ],
          "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "allowance",
          "inputs": [
            { "name": "owner", "type": "address", "internalType": "address" },
            { "name": "spender", "type": "address", "internalType": "address" }
          ],
          "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "approve",
          "inputs": [
            { "name": "spender", "type": "address", "internalType": "address" },
            { "name": "amount", "type": "uint256", "internalType": "uint256" }
          ],
          "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "transferFrom",
          "inputs": [
            { "name": "from", "type": "address", "internalType": "address" },
            { "name": "to", "type": "address", "internalType": "address" },
            { "name": "amount", "type": "uint256", "internalType": "uint256" }
          ],
          "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "mint",
          "inputs": [
            { "name": "to", "type": "address", "internalType": "address" },
            { "name": "amount", "type": "uint256", "internalType": "uint256" }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        }
      ],
      "inheritedFunctions": {}
    }
  }
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;